// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjfakkcezrgjfipcsams.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqZmFra2NlenJnamZpcGNzYW1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NTQ5NTcsImV4cCI6MjA2NzAzMDk1N30.rXrk0q9h06HWjr_4JWdmmYrqm6MPhu1_3JCMfhLEpC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});